---
version: "2"
run:
  allow-parallel-runners: true
linters:
  enable:
    - "bidichk"
    - "bodyclose"
    - "errcheck"
    - "errname"
    - "errorlint"
    - "gocritic"
    - "goprintffuncname"
    - "gosec"
    - "govet"
    - "importas"
    - "ineffassign"
    - "makezero"
    - "prealloc"
    - "predeclared"
    - "promlinter"
    - "revive"
    - "rowserrcheck"
    - "spancheck"
    - "staticcheck"
    - "tagalign"
    - "testifylint"
    - "tparallel"
    - "unconvert"
    - "usetesting"
    - "wastedassign"
    - "whitespace"
    - "unused"
  settings:
    staticcheck:
      checks:
        - "all"
  exclusions:
    generated: "lax"
    presets:
      - "comments"
      - "common-false-positives"
      - "legacy"
      - "std-error-handling"
formatters:
  enable:
    - "gci"
    - "gofumpt"
    - "goimports"
  settings:
    gci:
      sections:
        - "standard"
        - "default"
        - "prefix(github.com/authzed)"
        - "localmodule"
    goimports:
      local-prefixes:
        - "github.com/authzed/controller-idioms"
  exclusions:
    generated: "lax"
    paths:
      - "third_party$"
      - "builtin$"
      - "examples$"
