---
run:
  timeout: "5m"
output:
  sort-results: true
linters:
  enable:
    - "bidichk"
    - "bodyclose"
    - "errcheck"
    - "errname"
    - "errorlint"
    - "gofumpt"
    - "goimports"
    - "goprintffuncname"
    - "gosec"
    - "gosimple"
    - "govet"
    - "importas"
    - "ineffassign"
    - "makezero"
    - "prealloc"
    - "predeclared"
    - "promlinter"
    - "revive"
    - "rowserrcheck"
    - "staticcheck"
    - "stylecheck"
    - "tenv"
    - "typecheck"
    - "unconvert"
    - "unused"
    - "wastedassign"
    - "whitespace"
