---
name: "Lint"
on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - "!dependabot/*"
      - "main"
  pull_request:
    branches: ["*"]
env:
  GO_VERSION: "~1.20.7"
jobs:
  go-lint:
    name: "Lint Go"
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v4"
      - uses: "authzed/actions/setup-go@main"
        with:
          go-version: "${{ env.GO_VERSION }}"
      - uses: "magefile/mage-action@v3"
        with:
          version: "latest"
          args: "lint:go"
      # golangci-lint is kept out of the module for now, since it needs to be
      # run from root and would pollute the module's dependencies
      - uses: "authzed/actions/golangci-lint@main"

  extra-lint:
    name: "Lint YAML & Markdown"
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v4"
      - uses: "authzed/actions/setup-go@main"
        with:
          go-version: "${{ env.GO_VERSION }}"
      - uses: "magefile/mage-action@v3"
        with:
          version: "latest"
          args: "lint:extra"
